spring.application.name=bff-service
server.port=8080

smartlogix.envio.url=http://localhost:8081
smartlogix.inventario.url=http://localhost:8082
smartlogix.pedidos.url=http://localhost:8083
smartlogix.cliente.url=http://localhost:8084